### ISSUE TITLE
Compiling a file with just a closing paren crashes the parser

### ISSUE THREAD

**Issue by agroce** [ethereum/fe#209]
Compiling a file with just a closing paren crashes the parser:

```
)
```

```
> target/debug/fe crash.fe
Warning: bytecode output requires 'solc-backend' feature. Try `cargo build --release --features solc-backend`. Skipping.
thread 'main' panicked at 'attempt to subtract with overflow', parser/src/tokenizer/tokenize.rs:314:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c0b64d97beebb09325b5587abed39f4f1621026f/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/c0b64d97beebb09325b5587abed39f4f1621026f/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/c0b64d97beebb09325b5587abed39f4f1621026f/library/core/src/panicking.rs:50:5
   3: fe_parser::tokenizer::tokenize::tokenize
   4: fe_parser::get_parse_tokens
   5: fe_compiler::compile
   6: fe::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
```

On latest github master, built with

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer (we've found more than 50 bugs (that were worth fixing, and have been fixed) in solc using this afl variant) + afl.rs.

Not sure if you care about this kind of simple parser bug, but checking what your interest-level in fuzzing-detected bugs might be.

**Comment by sbillig** [comment]
The new parser handles this fine
```
Unable to compile ../eth/agroce-209.fe.
error: Unmatched right parenthesis
  ┌─ ../eth/agroce-209.fe:1:1
  │
1 │ )
  │ ^

error: failed to parse module
  ┌─ ../eth/agroce-209.fe:1:1
  │
1 │ )
  │ ^ unexpected token
  │
  = Note: expected import, contract, struct, type, or event
```
