### ISSUE TITLE
byte index 6 is out of bounds of `ir56` at compiler/src/abi/builder.rs:181:41

### ISSUE THREAD

**Issue by agroce** [ethereum/fe#213]
Compiling this file:

```
contract Foo:
    pub def bar(x: i256, y: ir56) -> i256:
        return x - y
```

```
Warning: bytecode output requires 'solc-backend' feature. Try `cargo build --release --features solc-backend`. Skipping.
thread 'main' panicked at 'byte index 6 is out of bounds of `ir56`', compiler/src/abi/builder.rs:181:41
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c0b64d97beebb09325b5587abed39f4f1621026f/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/c0b64d97beebb09325b5587abed39f4f1621026f/library/core/src/panicking.rs:92:14
   2: core::str::slice_error_fail
   3: fe_compiler::abi::builder::type_desc
   4: fe_compiler::abi::builder::func_def_arg
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
```

On latest github master, built with

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer (we've found more than 50 bugs (that were worth fixing, and have been fixed) in solc using this afl variant) + afl.rs.

This might be a more interesting type of bug, if you think fe is ready for fuzzing at all.

**Comment by cburgdorf** [comment]
Fixed by #217
