### ISSUE TITLE
Reject numbers with a decimal point eg `0.15`

### ISSUE THREAD

**Issue by agroce** [ethereum/fe#224]
Compiling this file:

```
contract Foo:
     pub def bar() -> u256:
        my_array: u256[3]
        my_array[2] >.15
        sum: u256 = 0
        return sum
```

```
thread 'main' panicked at 'Yul compilation failed: {"errors":[{"component":"general","formattedMessage":"ParserError: Invalid number literal.\n --> input.yul:1:252:\n  |\n1 |  ... n(add($my_array, mul(2, 32)), 32), .15)) let $sum := 0 { return_val := $s ...\n  |                                         ^^^\n\n","message":"Invalid number literal.","severity":"error","sourceLocation":{"end":254,"file":"input.yul","start":251},"type":"ParserError"},{"component":"general","formattedMessage":"ParserError: Expected keyword \"data\" or \"object\" or \"}\".\n --> input.yul:1:252:\n  |\n1 |  ... n(add($my_array, mul(2, 32)), 32), .15)) let $sum := 0 { return_val := $s ...\n  |                                         ^^^\n\n","message":"Expected keyword \"data\" or \"object\" or \"}\".","severity":"error","sourceLocation":{"end":254,"file":"input.yul","start":251},"type":"ParserError"}]}', compiler/src/lib.rs:45:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c0b64d97beebb09325b5587abed39f4f1621026f/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/c0b64d97beebb09325b5587abed39f4f1621026f/library/std/src/panicking.rs:435:5
   2: fe_compiler::compile
   3: fe::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
```

On latest github master, built with

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer

**Comment by sbillig** [comment]
The `.15` is now rejected by the parser as an unexpected character, but changing it to `0.15` hits a `todo!()` panic in the parser that should be fixed.

**Comment by Y-Nak** [comment]
It seems fixed in the current master.

```python
contract Foo:
     pub fn bar() -> u256:
        let my_array: Array<u256, 3>
        my_array[2] >0.15
        let sum: u256 = 0
        return sum
```

Fe compiler reports 
```
error: floats not supported
  ┌─ foo.fe:4:22
  │
4 │         my_array[2] >0.15
  │                      ^^^^
```
