### ISSUE TITLE
Yul compilation failed: TypeError: Number literal too large (> 256 bits)

### ISSUE THREAD

**Issue by agroce** [ethereum/fe#225]
Compiling this file:

```
contract  ERC20:
  pub def bar():
       888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888
```

```
thread 'main' panicked at 'Yul compilation failed: {"errors":[{"component":"general","formattedMessage":"TypeError: Number literal too large (> 256 bits)\n --> input.yul:1:168:\n  |\n1 |  ... e\" { code { function $$bar() { pop(888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888) } function avail() -> ptr { ptr : ...\n  |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n","message":"Number literal too large (> 256 bits)","severity":"error","sourceLocation":{"end":284,"file":"input.yul","start":167},"type":"TypeError"}]}', compiler/src/lib.rs:45:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c0b64d97beebb09325b5587abed39f4f1621026f/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/c0b64d97beebb09325b5587abed39f4f1621026f/library/std/src/panicking.rs:435:5
   2: fe_compiler::compile
   3: fe::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
```

On latest github master, built with

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer

**Comment by agroce** [comment]
obviously some of these are really just sub-optimal error messages, not bug-bugs, but removing them will make fuzzing triage easier, if you get a chance...

**Comment by cburgdorf** [comment]
Thanks for running these fuzzings! It's a bug in the sense that this shouldn't even enter Yul compilation. This should be detected in the analyzer pass and return an actual user error (not a panic).

**Comment by agroce** [comment]
right.  I figure these also may expose any missing checks on invariants that might indicate a miscompile, but that Yul may sometimes handle, so very nice to just flag them for inspection.
