### ISSUE TITLE
Yul compilation failed: count does not match number of values (1 vs. 0) [when function returns itself]

### ISSUE THREAD

**Issue by agroce** [ethereum/fe#227]
Compiling this file:

```
contract Foo:
    pub def foo():
       return self.foo()
```

```
thread 'main' panicked at 'Yul compilation failed: {"errors":[{"component":"general","formattedMessage":"DeclarationError: Variable count does not match number of values (1 vs. 0)\n --> input.yul:1:166:\n  |\n1 |  ... ime\" { code { function $$foo() { { return_val := $$foo() leave } } function avail() -> ptr  ...\n  |                                         ^^^^^^^^^^^^^^^^^^^^^\n\n","message":"Variable count does not match number of values (1 vs. 0)","severity":"error","sourceLocation":{"end":186,"file":"input.yul","start":165},"type":"DeclarationError"}]}', compiler/src/lib.rs:45:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c0b64d97beebb09325b5587abed39f4f1621026f/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/c0b64d97beebb09325b5587abed39f4f1621026f/library/std/src/panicking.rs:435:5
   2: fe_compiler::compile
   3: fe::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
```

On latest github master, built with

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer

**Comment by cburgdorf** [comment]
This was fixed recently. We didn't always properly handle the implicit return of empty tuples and this error was one of the symptoms. This does now compile.
