### ISSUE TITLE
Yul compilation failed: Expected keyword \"data\" or \"object\" or \"}\".

### ISSUE THREAD

**Issue by agroce** [ethereum/fe#230]
Compiling this file:

```
contract o:
    pub def a():
        """"""""""""""""""
```

```
thread 'main' panicked at 'Yul compilation failed: {"errors":[{"component":"general","formattedMessage":"ParserError: Expected keyword \"data\" or \"object\" or \"}\".\n --> input.yul:1:4298:\n  |\n1 |  ... e26b92190113138f72403f6bc45c844\" \"\"\"\"\"\"\"\"\"\"\"\"\"\" } data \"0xb581cabea89bad ...\n  |                                         ^^\n\n","message":"Expected keyword \"data\" or \"object\" or \"}\".","severity":"error","sourceLocation":{"end":4299,"file":"input.yul","start":4297},"type":"ParserError"}]}', compiler/src/lib.rs:45:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c0b64d97beebb09325b5587abed39f4f1621026f/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/c0b64d97beebb09325b5587abed39f4f1621026f/library/std/src/panicking.rs:435:5
   2: fe_compiler::compile
   3: fe::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
```

On latest github master, built with

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer

**Comment by sbillig** [comment]
This invalid syntax is caught by the new parser (#346)
