### ISSUE TITLE
Yul compilation failed: Expected 'StringLiteral' but got 'ILLEGAL'

### ISSUE THREAD

**Issue by agroce** [ethereum/fe#238]
Compiling the attached file produces
[stringilegal.zip](https://github.com/ethereum/fe/files/5945223/stringilegal.zip)

```
thread 'main' panicked at 'Yul compilation failed: {"errors":[{"component":"general","formattedMessage":"ParserError: Expected 'StringLiteral' but got 'ILLEGAL'\n --> input.yul:1:4296:\n  |\n1 |  ... 8cc210f69cffaf88e431b31864eac4ba7\" \"\u0017''''''''''''''''''''''''''''''''\" } ...\n  |                                         ^^\n\n","message":"Expected 'StringLiteral' but got 'ILLEGAL'","severity":"error","sourceLocation":{"end":4297,"file":"input.yul","start":4295},"type":"ParserError"}]}', compiler/src/lib.rs:45:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c0b64d97beebb09325b5587abed39f4f1621026f/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/c0b64d97beebb09325b5587abed39f4f1621026f/library/std/src/panicking.rs:435:5
   2: fe_compiler::compile
   3: fe::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
```

On latest github master, built with

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer (we've found more than 50 bugs (that were worth fixing, and have been fixed) in solc using this afl variant) + afl.rs.

**Comment by cburgdorf** [comment]
Looks like a cases of #329

**Comment by cburgdorf** [comment]
This is now properly recognized as invalid byte sequence
