### ISSUE TITLE
Yul compilation failed: Illegal token: Identifier-start is not allowed at end of a number.

### ISSUE THREAD

**Issue by agroce** [ethereum/fe#240]
Compiling this file:

```
contract Foo:
    pub def bar() -> u256:
        counter: u256 = 0J
        return counter
```

```
thread 'main' panicked at 'Yul compilation failed: {"errors":[{"component":"general","formattedMessage":"ParserError: Illegal token: Identifier-start is not allowed at end of a number.\n --> input.yul:1:194:\n  |\n1 |  ... () -> return_val { let $counter := 0J { return_val := $counter leave }  ...\n  |                                         ^\n\n","message":"Illegal token: Identifier-start is not allowed at end of a number.","severity":"error","sourceLocation":{"end":194,"file":"input.yul","start":193},"type":"ParserError"},{"component":"general","formattedMessage":"ParserError: Expected keyword \"data\" or \"object\" or \"}\".\n --> input.yul:1:194:\n  |\n1 |  ... () -> return_val { let $counter := 0J { return_val := $counter leave }  ...\n  |                                         ^\n\n","message":"Expected keyword \"data\" or \"object\" or \"}\".","severity":"error","sourceLocation":{"end":194,"file":"input.yul","start":193},"type":"ParserError"}]}', compiler/src/lib.rs:45:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c0b64d97beebb09325b5587abed39f4f1621026f/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/c0b64d97beebb09325b5587abed39f4f1621026f/library/std/src/panicking.rs:435:5
   2: fe_compiler::compile
   3: fe::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
```

On latest github master, built with

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer (we've found more than 50 bugs (that were worth fixing, and have been fixed) in solc using this afl variant) + afl.rs.

**Comment by cburgdorf** [comment]
This has been fixed by https://github.com/ethereum/fe/commit/7bd839b5b0d9908654719258f42c0b94086047ef
