### ISSUE TITLE
Yul compilation failed: Invalid number literal / Expected keyword \"data\" or \"object\" or \" (different cause, looks like, than before)

### ISSUE THREAD

**Issue by agroce** [ethereum/fe#292]
Compiling this file:

```
contract o:
 pub def r()->i256:return i256(3_9)
```

```
thread 'main' panicked at 'Yul compilation failed: {"errors":[{"component":"general","formattedMessage":"ParserError: Invalid number literal.\n --> input.yul:1:185:\n  |\n1 |  ... () -> return_val { { return_val := 3_9 leave } } function avail() -> ptr  ...\n  |                                         ^^^\n\n","message":"Invalid number literal.","severity":"error","sourceLocation":{"end":187,"file":"input.yul","start":184},"type":"ParserError"},{"component":"general","formattedMessage":"ParserError: Expected keyword \"data\" or \"object\" or \"}\".\n --> input.yul:1:185:\n  |\n1 |  ... () -> return_val { { return_val := 3_9 leave } } function avail() -> ptr  ...\n  |                                         ^^^\n\n","message":"Expected keyword \"data\" or \"object\" or \"}\".","severity":"error","sourceLocation":{"end":187,"file":"input.yul","start":184},"type":"ParserError"}]}', compiler/src/lib.rs:48:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/panicking.rs:435:5
   2: fe_compiler::compile
   3: fe::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
```

On latest github master, built with

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer

**Comment by cburgdorf** [comment]
Just cross linking that writing numbers with underscores should be supported long term (https://github.com/ethereum/fe/issues/149)

**Comment by sbillig** [comment]
The "new" parser rejects the `3_9` number now, so this code is rejected gracefully. Explicit support for underscore characters is tracked in #149.
