### ISSUE TITLE
Yul compilation failed: Top-level expressions are not supposed to return values (this expression returns 1 value). Use ``pop()`` or assign them.

### ISSUE THREAD

**Issue by agroce** [ethereum/fe#307]
Compiling this file:

```
contract C:
 pub def __init__(t:address)->u256:
     return 0
```

```
thread 'main' panicked at 'Yul compilation failed: {"errors":[{"component":"general","formattedMessage":"TypeError: Top-level expressions are not supposed to return values (this expression returns 1 value). Use ``pop()`` or assign them.\n --> input.yul:1:323:\n  |\n1 |  ... _val { { return_val := 0 leave } } $$__init__(abi_decode_address_mem(params_start_mem, 0)) function contract_create2(data_ptr ...\n  |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n","message":"Top-level expressions are not supposed to return values (this expression returns 1 value). Use ``pop()`` or assign them.","severity":"error","sourceLocation":{"end":377,"file":"input.yul","start":322},"type":"TypeError"}]}', compiler/src/lib.rs:48:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/panicking.rs:435:5
   2: fe_compiler::compile
   3: fe::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
```

On latest github master, built with

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer

**Comment by cburgdorf** [comment]
Nice catch!

**Comment by agroce** [comment]
This one took close to 16 days of running the fuzzer to hit (and only detected in one of those runs)!
