### ISSUE TITLE
failed to analyze lowered AST: SemanticError { kind: AlreadyDefined, context: [] } at compiler/src/lib.rs:55:59

### ISSUE THREAD

**Issue by agroce** [ethereum/fe#438]
Compiling this file:

```
contract Foo:
        my_other_tuple: (address, address)
struct tuple_address_address:
        value: u256
```

```
thread 'main' panicked at 'failed to analyze lowered AST: SemanticError { kind: AlreadyDefined, context: [] }', compiler/src/lib.rs:54:60
stack backtrace:
   0:     0x556704b0e390 - std::backtrace_rs::backtrace::libunwind::trace::h9d49145f95eb5894
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x556704b0e390 - std::backtrace_rs::backtrace::trace_unsynchronized::hab1d020365bb6864
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x556704b0e390 - std::sys_common::backtrace::_print_fmt::h7659588431e304bd
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x556704b0e390 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h09f4a9e3befae3c7
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x556704b280ec - core::fmt::write::hf3fdfde304b9a088
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/core/src/fmt/mod.rs:1092:17
   5:     0x556704b0b2f2 - std::io::Write::write_fmt::h1cb850689c7116f0
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/io/mod.rs:1568:15
   6:     0x556704b10555 - std::sys_common::backtrace::_print::hdbccd5aa093ba544
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x556704b10555 - std::sys_common::backtrace::print::hc639c4f320222558
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x556704b10555 - std::panicking::default_hook::{{closure}}::hdb012dd7a485bb5d
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/panicking.rs:208:50
   9:     0x556704b10003 - std::panicking::default_hook::h75facbce77b6ba91
                               at /rustc/9c09c1f7cfcf9de0522bcd1cfda32b552195c464/library/std/src/panicking.rs:225:9
  10:     0x55670423ef1f - fe_compiler::errors::DEFAULT_PANIC_HOOK::{{closure}}::{{closure}}::hd71e839699e0bfd6

You've hit an internal compiler error. This is a bug in the Fe compiler.
Fe is still under heavy development, and isn't yet ready for production use.

If you would, please report this bug at the following URL:
  https://github.com/ethereum/fe/issues/new
Aborted
```

I'm not sure this crashes on latest.  When I try to build, I get:

```
   Compiling typenum v1.13.0
   Compiling semver v1.0.0
   Compiling num-traits v0.2.14
   Compiling regex v1.5.2
   Compiling serde v1.0.125
   Compiling rand v0.7.3
   Compiling vec1 v1.8.0
   Compiling solc v0.1.0 (https://github.com/g-r-a-n-t/solc-rust#fcb91059)
error[E0658]: the `unsafe_op_in_unsafe_fn` lint is unstable
  --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/semver-1.0.0/src/lib.rs:66:50
   |
66 | #![cfg_attr(not(no_unsafe_op_in_unsafe_fn_lint), deny(unsafe_op_in_unsafe_fn))]
   |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #71668 <https://github.com/rust-lang/rust/issues/71668> for more information
   = help: add `#![feature(unsafe_block_in_unsafe_fn)]` to the crate attributes to enable

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `semver`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer

**Comment by agroce** [comment]
Yes, after a rust uninstall/install nightly, I was able to build (though not the solc backend, solc compile fails due to some missing file...) and:

```
Warning: bytecode output requires 'solc-backend' feature. Try `cargo build --release --features solc-backend`. Skipping.
thread 'main' panicked at 'failed to analyze lowered AST: AnalyzerError { diagnostics: [], classic: Some(SemanticError { kind: AlreadyDefined, context: [] }) }', compiler/src/lib.rs:55:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

You've hit an internal compiler error. This is a bug in the Fe compiler.
Fe is still under heavy development, and isn't yet ready for production use.

If you would, please report this bug at the following URL:
  https://github.com/ethereum/fe/issues/new
Aborted
```

**Comment by sbillig** [comment]
> error[E0658]: the `unsafe_op_in_unsafe_fn` lint is unstable

This was stabilized in rust 1.52; it should build on non-nightly rust if you `rustup update stable`.

**Comment by Y-Nak** [comment]
I'll work on this.
ref: #377

**Comment by Y-Nak** [comment]
I'll work on #326 first and rewrite lowering tests, currently which doesn't work when an unexpected symbol is prepended in lowering pass like `$`.

**Comment by cburgdorf** [comment]
This particular issue doesn't seem to be a problem anymore with the generated tuple being named `$tuple_address_address_` now. There is still #477 with ideas to generally improve the naming strategy but it seems that this concrete bug is already fixed.
