### ISSUE TITLE
Yul compilation failed: ParserError: Expected 'StringLiteral' but got 'ILLEGAL'

### ISSUE THREAD

**Issue by agroce** [ethereum/fe#448]
Compiling this file:

```
contract o:
 pub def g(baz:u256):
  assert baz>5,""
```

```
Error: {"errors":[{"component":"general","formattedMessage":"ParserError: Expected 'StringLiteral' but got 'ILLEGAL'\n --> input.yul:1:21094:\n  |\n1 |  ... 85a35cd5bb6386747517ef7e53b15e287\" \"\u0003\" } data \"0x69c322e3248a5dfc29d73c5 ...\n  |                                         ^^\n\n","message":"Expected 'StringLiteral' but got 'ILLEGAL'","severity":"error","sourceLocation":{"end":21095,"file":"input.yul","start":21093},"type":"ParserError"}]}
thread 'main' panicked at 'Yul compilation failed.', compiler/src/lib.rs:69:17
stack backtrace:
   0:     0x557929704eb0 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x557929704eb0 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x557929704eb0 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x557929704eb0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55792971e28f - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x557929702912 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x557929707045 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x557929707045 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x557929707045 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x557929706af3 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x557928dabbdf - fe_compiler::errors::DEFAULT_PANIC_HOOK::{{closure}}::{{closure}}::hbebb7f70ffef6630

You've hit an internal compiler error. This is a bug in the Fe compiler.
Fe is still under heavy development, and isn't yet ready for production use.

If you would, please report this bug at the following URL:
  https://github.com/ethereum/fe/issues/new
Aborted
```

Using

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer

**Comment by agroce** [comment]
There seem to be variations, with a missing ending quote and things, that trigger very similar errors that cause some issues for the fuzzer triage for some reason (the parser isn't perfect, so I think it gets confused on the ILLEGAL message somewhere), FYI.  I'll let you know if this one gets fixed and those aren't handled also.  In the meantime, for fuzzer triage improvement, this would not be a bad issue to fix (right now I have to manually deal with the repeats of this).

**Comment by agroce** [comment]
Ok, handled the triage.  This is a variant that crashes with a different signature:

```
contract o:
 pub def g(baz:u256):
  assert baz>5,"
"
```
