### ISSUE TITLE
unit type is not abi encodable at crates/analyzer/src/namespace/types.rs:598:27

### ISSUE THREAD

**Issue by agroce** [ethereum/fe#480]
Compiling this file:

```
contract o:
 d:(())
```

```
thread 'main' panicked at 'unit type is not abi encodable', crates/analyzer/src/namespace/types.rs:598:27
stack backtrace:
   0:     0x5649ca04f7d0 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5649ca04f7d0 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5649ca04f7d0 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5649ca04f7d0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5649ca0689bf - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x5649ca04d232 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x5649ca051965 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5649ca051965 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5649ca051965 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x5649ca051413 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x5649c9f9c326 - fe_common::panic::DEFAULT_PANIC_HOOK::{{closure}}::{{closure}}::hc9c371f2106ced58

You've hit an internal compiler error. This is a bug in the Fe compiler.
Fe is still under heavy development, and isn't yet ready for production use.

If you would, please report this bug at the following URL:
  https://github.com/ethereum/fe/issues/new
Aborted
```

Using

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer

**Comment by cburgdorf** [comment]
I looked into this yesterday but I'm not exactly sure how to fix it. The reason for this error is because unit types aren't currently ABI encodable which causes to blow up here

https://github.com/ethereum/fe/blob/fa345453c7589fd480369be8bd11000b95e30aba/crates/analyzer/src/namespace/types.rs#L603

That's because of the struct that contains fields of type `()`

https://github.com/ethereum/fe/blob/fa345453c7589fd480369be8bd11000b95e30aba/crates/yulgen/src/runtime/mod.rs#L52-L57

So the following call then starts the trouble

https://github.com/ethereum/fe/blob/fa345453c7589fd480369be8bd11000b95e30aba/crates/yulgen/src/runtime/mod.rs#L68


I'm wondering how we want to address this. We could prevent fields of type `()` in structs but I'm not sure if that's the right call since e.g. in Rust it is perfectly valid to have something like `let x = ((),())`.

The [abi-spec](https://docs.soliditylang.org/en/latest/abi-spec.html) explicitly mentions that zero sized tuples are valid so I'm thinking we should just encode the unit type as an empty tuple. Thoughts @g-r-a-n-t ?

**Comment by Y-Nak** [comment]
fixed in https://github.com/ethereum/fe/pull/676
