### ISSUE TITLE
failed to analyze lowered AST (duplicate type name)

### ISSUE THREAD

**Issue by agroce** [ethereum/fe#531]
Compiling this file:

```
struct tuple_bool_address_:
 m:bool
contract o:
 e:(bool,address)
```

```
thread 'main' panicked at 'failed to analyze lowered AST: [Diagnostic { severity: Error, message: "duplicate type name", labels: [Label { style: Primary, span: Span { start: 0, end: 0 }, message: "`tuple_bool_address_` first defined here" }, Label { style: Secondary, span: Span { start: 0, end: 35 }, message: "`tuple_bool_address_` redefined here" }], notes: [] }]', crates/driver/src/lib.rs:62:51
stack backtrace:
   0:     0x5558642d6100 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5558642d6100 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5558642d6100 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5558642d6100 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5558642eee4f - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x5558642d3a22 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x5558642d8295 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5558642d8295 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5558642d8295 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x5558642d7d43 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x555864221b66 - fe_common::panic::DEFAULT_PANIC_HOOK::{{closure}}::{{closure}}::hfa0d7480b545d3da

You've hit an internal compiler error. This is a bug in the Fe compiler.
Fe is still under heavy development, and isn't yet ready for production use.

If you would, please report this bug at the following URL:
  https://github.com/ethereum/fe/issues/new
Aborted
```

Using

```
[profile.dev]
debug = true
panic = "abort"
```

for fuzzing.  Using https://github.com/agroce/afl-compiler-fuzzer

**Comment by agroce** [comment]
BTW, I found that from a 23 day long, 180M+ executions, fuzz of the compiler.

So I spun up a docker copy, grabbed the latest code, and checked to see if it's still a bug (since the code is 23 days stale).

Nope.

Oh well, whatever. this was a few days ago.

Then I had a brainstorm, spun up a copy, minimized the failing input, and tried the shrunk version -- which, sure enough, IS a bug, still, with same symptoms. but the larger thing the fuzzer found doesn't get far enough to break things, due to improved compiler syntax checking for unrelated bad code.

**Comment by agroce** [comment]
I have a feeling people triaging long fuzzer runs on under-development targets probably throw out a tolerable number of bugs due to this kind of thing. I wonder how many I may have lost (and, who knows, never rediscovered).

Fuzzing/triage best practices are really such a black art, experience as only teacher. somebody should write a book.
