### ISSUE TITLE
Assigning array elem to array elem causes ICE

### ISSUE THREAD

**Issue by Y-Nak** [ethereum/fe#650]
### What is wrong?

Please include information like:

* full output of the error you received
```
thread 'main' panicked at 'expression is not an identifier get_array_item($arr1, 4, 1, 4)', crates/yulgen/src/mappers/assignments.rs:81:9
```
<details>
<summary>back trace</summary>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: fe_yulgen::mappers::assignments::expr_as_ident
   3: fe_yulgen::mappers::assignments::assign
   4: fe_yulgen::mappers::functions::func_stmt
   5: fe_yulgen::mappers::functions::multiple_func_stmt::{{closure}}
   6: core::iter::adapters::map::map_fold::{{closure}}
   7: core::iter::traits::iterator::Iterator::fold
   8: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   9: core::iter::traits::iterator::Iterator::for_each
  10: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
  11: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
  12: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  13: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
  14: core::iter::traits::iterator::Iterator::collect
  15: fe_yulgen::mappers::functions::multiple_func_stmt
  16: fe_yulgen::db::queries::functions::function_def
  17: <fe_yulgen::db::FunctionDefQuery as salsa::plumbing::QueryFunction>::execute
  18: salsa::derived::slot::Slot<Q,MP>::read_upgrade::{{closure}}
  19: salsa::runtime::Runtime::execute_query_implementation
  20: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  21: salsa::derived::slot::Slot<Q,MP>::read
  22: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  23: salsa::QueryTable<Q>::try_get
  24: salsa::QueryTable<Q>::get
  25: <DB as fe_yulgen::db::YulgenDb>::function_def::__shim
  26: <DB as fe_yulgen::db::YulgenDb>::function_def
  27: fe_yulgen::db::queries::contracts::build_dependency_graph::{{closure}}
  28: fe_analyzer::namespace::items::walk_local_dependencies
  29: fe_yulgen::db::queries::contracts::build_dependency_graph
  30: fe_yulgen::db::queries::contracts::contract_object
  31: <fe_yulgen::db::ContractObjectQuery as salsa::plumbing::QueryFunction>::execute
  32: salsa::derived::slot::Slot<Q,MP>::read_upgrade::{{closure}}
  33: salsa::runtime::Runtime::execute_query_implementation
  34: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  35: salsa::derived::slot::Slot<Q,MP>::read
  36: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  37: salsa::QueryTable<Q>::try_get
  38: salsa::QueryTable<Q>::get
  39: <DB as fe_yulgen::db::YulgenDb>::contract_object::__shim
  40: <DB as fe_yulgen::db::YulgenDb>::contract_object
  41: fe_yulgen::mappers::module::module::{{closure}}
  42: core::iter::traits::iterator::Iterator::fold
  43: fe_yulgen::mappers::module::module
  44: fe_yulgen::db::queries::compile_module
  45: <fe_yulgen::db::CompileModuleQuery as salsa::plumbing::QueryFunction>::execute
  46: salsa::derived::slot::Slot<Q,MP>::read_upgrade::{{closure}}
  47: salsa::runtime::Runtime::execute_query_implementation
  48: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  49: salsa::derived::slot::Slot<Q,MP>::read
  50: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  51: salsa::QueryTable<Q>::try_get
  52: salsa::QueryTable<Q>::get
  53: <DB as fe_yulgen::db::YulgenDb>::compile_module::__shim
  54: <DB as fe_yulgen::db::YulgenDb>::compile_module
  55: fe_yulgen::compile
  56: fe_driver::compile_module
  57: fe::main
  58: core::ops::function::FnOnce::call_once
```
</details>

* what command you ran
`RUST_BACKTRACE=1 cargo run {file}`

* the code that caused the failure (see [this link](https://help.github.com/articles/basic-writing-and-formatting-syntax/) for help with formatting code)

```python
contract Foo:
    pub fn bar(self):
        let arr1: Array<i32, 4>
        let arr2: Array<i32, 4>
        arr1[1] = arr2[1]
```

**Comment by Y-Nak** [comment]
Oops, This is a duplicate of #590
