### ISSUE TITLE
[ICE] Compiler panics when trying to implement trait on undefined types

### ISSUE THREAD

**Issue by Y-Nak** [ethereum/fe#816]
### What is wrong?
```rust
trait Foo {
    fn x(self) -> i32;
}

impl Foo for Missing {
    fn x(self) -> i32 {
        return 1
    }
}
```

<details><summary>backtrace</summary>

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TypeError(DiagnosticVoucher(PhantomData))', crates/analyzer/src/db/queries/module.rs:120:85
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::unwrap
   4: fe_analyzer::db::queries::module::module_all_impls::{{closure}}
   5: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
   6: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::find_map
   7: <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
   8: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
   9: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  10: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
  11: core::iter::traits::iterator::Iterator::collect
  12: <I as alloc::rc::ToRcSlice<T>>::to_rc_slice
  13: <alloc::rc::Rc<[T]> as core::iter::traits::collect::FromIterator<T>>::from_iter
  14: core::iter::traits::iterator::Iterator::collect
  15: fe_analyzer::db::queries::module::module_all_impls
  16: <fe_analyzer::db::ModuleAllImplsQuery as salsa::plumbing::QueryFunction>::execute
  17: salsa::derived::slot::Slot<Q,MP>::read_upgrade::{{closure}}
  18: salsa::runtime::Runtime::execute_query_implementation
  19: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  20: salsa::derived::slot::Slot<Q,MP>::read
  21: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  22: salsa::QueryTable<Q>::try_get
  23: salsa::QueryTable<Q>::get
  24: <DB as fe_analyzer::db::AnalyzerDb>::module_all_impls::__shim
  25: <DB as fe_analyzer::db::AnalyzerDb>::module_all_impls
  26: fe_analyzer::db::queries::module::module_impl_map
  27: <fe_analyzer::db::ModuleImplMapQuery as salsa::plumbing::QueryFunction>::execute
  28: salsa::derived::slot::Slot<Q,MP>::read_upgrade::{{closure}}
  29: salsa::runtime::Runtime::execute_query_implementation
  30: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  31: salsa::derived::slot::Slot<Q,MP>::read
  32: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::try_fetch
  33: salsa::QueryTable<Q>::try_get
  34: salsa::QueryTable<Q>::get
  35: <DB as fe_analyzer::db::AnalyzerDb>::module_impl_map::__shim
  36: <DB as fe_analyzer::db::AnalyzerDb>::module_impl_map
  37: fe_analyzer::namespace::items::ModuleId::sink_diagnostics
  38: fe_analyzer::namespace::items::ModuleId::diagnostics
  39: fe_driver::compile_single_file
  40: fe::task::build::build_single_file
  41: fe::task::build::build
  42: fe::main
  43: core::ops::function::FnOnce::call_once
```
</details>

**Comment by cburgdorf** [comment]
This doesn't appear to be a problem anymore:

```
Unable to compile foo.fe.
error: undefined type
  ┌─ foo.fe:5:14
  │
5 │ impl Foo for Missing {
  │              ^^^^^^^ `Missing` has not been defined

```
