### ISSUE TITLE
compiler panic: `panicked at 'missing impl', crates/mir/src/lower/function.rs:1036:22`

### ISSUE THREAD

**Issue by g-r-a-n-t** [ethereum/fe#888]
```
// panicked at 'missing impl', crates/mir/src/lower/function.rs:1036:22
pub fn write<T: MemoryBufferWrite>(mut self, value: T) {
  value.write_buf(writer: self)
}
```

https://github.com/g-r-a-n-t/fe/blob/bd18a94b0c295105c598918c349a2781b35e1978/crates/library/std/src/buf.fe#L151-L154

_Originally posted by @cburgdorf in https://github.com/ethereum/fe/pull/885#discussion_r1200841476_

**Comment by sbillig** [comment]
Defunct. mir crate is no longer used
